create table public.registration_attempts (
  id bigint generated by default as identity primary key,
  ip_address text not null,
  attempted_at timestamptz not null default now()
);

create index registration_attempts_ip_attempted_idx
  on public.registration_attempts (ip_address, attempted_at desc);

alter table public.registration_attempts enable row level security;

revoke all on table public.registration_attempts from anon, authenticated;
grant select, insert, delete on table public.registration_attempts to service_role;
